name: ThirdParty-ActiveCommunities
on:
  schedule:
    - cron: '0 11 * * 1-5'
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install && npm install -g @lhci/cli@0.8.0
      - run: npm run build:thirdparty:activecommunities
      - run: npm run test:thirdparty:activecommunities
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
