name: apps.saultstemarie.ca-shop
on:
  push:
  schedule:
    - cron: '0 11,16 * * 1-5'
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install && npm install -g @lhci/cli@0.6.x
      - run: lhci autorun --config sites/appsSaultstemarieCa-shop/lighthouserc.js
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
