name: GFLGardens.ca
on:
  schedule:
    - cron: '0 10 * * 1-5'
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install && npm install -g @lhci/cli@0.8.0
      - run: npm run build:website:gflgardens
      - run: npm run test:website:gflgardens
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
