name: GFLGardens.ca
on:
  push:
  schedule:
    - cron: '0 11,16 * * 1-5'
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install && npm install -g @lhci/cli@0.7.1
      - run: lhci autorun --config sites/gflgardensCa/lighthouserc.js
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
