name: SaultSteMarie.ca
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,20 * * 1-5'
jobs:
  lighthouseci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g @lhci/cli@0.9.x
      - run: npm ci
      - run: npm run build:website:saultstemarie
      - run: npm run test:website:saultstemarie
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
