name: ShapeTheSault.ca
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g npm@7 @lhci/cli@0.8.0
      - run: npm ci
      - run: npm run build:other:shapethesault
      - run: npm run test:other:shapethesault
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
