name: WelcomeToSSM.com
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,13 * * 1-5'
jobs:
  lighthouseci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g npm@7 @lhci/cli@0.9.x
      - run: npm ci
      - run: npm run build:website:welcometossm
      - run: npm run test:website:welcometossm
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
